from __future__ import annotations

from enum import StrEnum

STRATEGY_VERSION_V24 = "intraday_v2_4"


class JournalDirection(StrEnum):
    LONG = "LONG"
    SHORT = "SHORT"


class SetupType(StrEnum):
    TREND_PULLBACK = "TREND_PULLBACK"
    BREAKOUT_RETEST = "BREAKOUT_RETEST"
    MOMENTUM_CONTINUATION = "MOMENTUM_CONTINUATION"
    VWAP_RECLAIM = "VWAP_RECLAIM"
    VWAP_REJECT = "VWAP_REJECT"
    SUPPORT_BOUNCE = "SUPPORT_BOUNCE"
    RESISTANCE_REJECTION = "RESISTANCE_REJECTION"
    RELATIVE_STRENGTH = "RELATIVE_STRENGTH"
    RELATIVE_WEAKNESS = "RELATIVE_WEAKNESS"
    COMPRESSION_EXPANSION = "COMPRESSION_EXPANSION"
    OPENING_RANGE_BREAKOUT = "OPENING_RANGE_BREAKOUT"
    UNKNOWN = "UNKNOWN"


class GateResult(StrEnum):
    PASS = "PASS"
    WARN = "WARN"
    FAIL = "FAIL"


class DataAvailability(StrEnum):
    AVAILABLE = "AVAILABLE"
    DATA_NOT_AVAILABLE = "DATA_NOT_AVAILABLE"


class DataConfidence(StrEnum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    UNKNOWN = "UNKNOWN"


class ConfigurationStatus(StrEnum):
    CONFIGURED = "CONFIGURED"
    NOT_CONFIGURED = "NOT_CONFIGURED"


class DataSLAResult(StrEnum):
    PASS = "PASS"
    WARN = "WARN"
    FAIL = "FAIL"
    NOT_CONFIGURED = "NOT_CONFIGURED"


class MicrostructureStatus(StrEnum):
    PASS = "PASS"
    WARN = "WARN"
    FAIL = "FAIL"
    DATA_NOT_AVAILABLE = "DATA_NOT_AVAILABLE"


class SampleType(StrEnum):
    DEVELOPMENT = "DEVELOPMENT"
    OOS = "OOS"
    FORWARD = "FORWARD"
    SHADOW = "SHADOW"


class FillStatus(StrEnum):
    FILLED = "FILLED"
    PARTIAL = "PARTIAL"
    UNCERTAIN = "UNCERTAIN"
    NOT_FILLED = "NOT_FILLED"


class TradeEventType(StrEnum):
    ENTRY = "ENTRY"
    STOP_MOVE = "STOP_MOVE"
    TP_MOVE = "TP_MOVE"
    PARTIAL_EXIT = "PARTIAL_EXIT"
    ADD = "ADD"
    REDUCE = "REDUCE"
    FULL_EXIT = "FULL_EXIT"
    THESIS_UPDATE = "THESIS_UPDATE"
    CANCEL = "CANCEL"
    OTHER = "OTHER"


class JournalStatus(StrEnum):
    ACTIVE = "ACTIVE"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"
    INCOMPLETE = "INCOMPLETE"


class StatisticalAdmissionStatus(StrEnum):
    NOT_CONFIGURED = "NOT_CONFIGURED"
    PASS = "PASS"
    FAIL = "FAIL"


class CalibrationStatus(StrEnum):
    UNCALIBRATED = "UNCALIBRATED"
    PRELIMINARY = "PRELIMINARY"
    CALIBRATED = "CALIBRATED"


class ProbabilityStatus(StrEnum):
    NOT_RELIABLY_CALIBRATED = "NOT_RELIABLY_CALIBRATED"
    CALIBRATED = "CALIBRATED"


class FinalClassification(StrEnum):
    TRADEABLE = "TRADEABLE"
    WATCH_ONLY = "WATCH_ONLY"
    SIGNAL_VALID_EXECUTION_INVALID = "SIGNAL_VALID_EXECUTION_INVALID"
    DATA_INSUFFICIENT = "DATA_INSUFFICIENT"
    REJECTED = "REJECTED"


class FinalDecision(StrEnum):
    ENTER_NOW = "ENTER_NOW"
    WAIT = "WAIT"
    NO_TRADE = "NO_TRADE"
    CANCEL = "CANCEL"


class AdversarialResult(StrEnum):
    PASS = "PASS"
    FAIL = "FAIL"
    WAIT = "WAIT"


class AuditStatus(StrEnum):
    PASS = "PASS"
    FAIL = "FAIL"


class KillSwitchState(StrEnum):
    NORMAL = "NORMAL"
    CAPITAL_PRESERVATION = "CAPITAL_PRESERVATION"


class HistoricalEvidenceStatus(StrEnum):
    AVAILABLE = "AVAILABLE"
    MISSING_HISTORICAL_EVIDENCE = "MISSING_HISTORICAL_EVIDENCE"


class SourceClass(StrEnum):
    OFFICIAL_REALTIME = "OFFICIAL_REALTIME"
    OFFICIAL_PUBLIC = "OFFICIAL_PUBLIC"
    BROKER_REALTIME = "BROKER_REALTIME"
    LICENSED_REALTIME = "LICENSED_REALTIME"
    AGGREGATED = "AGGREGATED"
    MANUAL_CONFIRMED = "MANUAL_CONFIRMED"
    UNKNOWN = "UNKNOWN"


class ContextType(StrEnum):
    FUNDAMENTAL = "FUNDAMENTAL"
    NEWS = "NEWS"
    CORPORATE_EVENT = "CORPORATE_EVENT"
    CROSS_ASSET = "CROSS_ASSET"


class DecisionAction(StrEnum):
    ENTER_NOW = "ENTER_NOW"
    MOVE_STOP = "MOVE_STOP"
    CLOSE_NOW = "CLOSE_NOW"
    INTRADAY_ANALYSIS = "INTRADAY_ANALYSIS"
    WATCH = "WATCH"
    LIMIT = "LIMIT"
    VERIFY_AT_BROKER = "VERIFY_AT_BROKER"


class TradingSessionState(StrEnum):
    CONTINUOUS = "CONTINUOUS"
    AUCTION = "AUCTION"
    HALTED = "HALTED"
    SUSPENDED = "SUSPENDED"
    RESUMPTION = "RESUMPTION"
    CLOSED = "CLOSED"
    UNKNOWN = "UNKNOWN"


class CostConfigurationStatus(StrEnum):
    CONFIGURED = "CONFIGURED"
    PARTIAL = "PARTIAL"
    NOT_CONFIGURED = "NOT_CONFIGURED"


class RiskBudgetStatus(StrEnum):
    CONFIGURED = "CONFIGURED"
    NOT_CONFIGURED = "NOT_CONFIGURED"


class CalculationReliability(StrEnum):
    RELIABLE = "RELIABLE"
    PROVISIONAL = "PROVISIONAL"
    NOT_RELIABLY_CALCULABLE = "NOT_RELIABLY_CALCULABLE"


class OpportunityRankingMode(StrEnum):
    CALIBRATED_EV = "CALIBRATED_EV"
    COLD_START_COMPOSITE = "COLD_START_COMPOSITE"
    NOT_RELIABLY_CALCULABLE = "NOT_RELIABLY_CALCULABLE"


class PathToTargetStatus(StrEnum):
    CLEAN = "CLEAN"
    ACCEPTABLE = "ACCEPTABLE"
    BLOCKED = "BLOCKED"
    UNKNOWN = "UNKNOWN"


class IntradayStrategyMode(StrEnum):
    INTRADAY = "INTRADAY"


class MarketTrendRegime(StrEnum):
    STRONG_UPTREND = "STRONG_UPTREND"
    UPTREND = "UPTREND"
    RANGE = "RANGE"
    DOWNTREND = "DOWNTREND"
    STRONG_DOWNTREND = "STRONG_DOWNTREND"


class VolatilityStateV24(StrEnum):
    HIGH_VOL = "HIGH_VOL"
    NORMAL_VOL = "NORMAL_VOL"
    LOW_VOL = "LOW_VOL"
    ABNORMAL = "ABNORMAL"


class EventStateV24(StrEnum):
    NORMAL = "NORMAL"
    NEWS_DRIVEN = "NEWS_DRIVEN"
    PANIC = "PANIC"
    DATA_NOT_AVAILABLE = "DATA_NOT_AVAILABLE"


class MarketBiasV24(StrEnum):
    STRONG_LONG = "STRONG_LONG"
    LONG = "LONG"
    NEUTRAL = "NEUTRAL"
    SHORT = "SHORT"
    STRONG_SHORT = "STRONG_SHORT"


class VolumeProfileStatus(StrEnum):
    AVAILABLE = "AVAILABLE"
    DATA_NOT_AVAILABLE = "DATA_NOT_AVAILABLE"


class StructureState(StrEnum):
    HH_HL = "HH_HL"
    LH_LL = "LH_LL"
    MIXED = "MIXED"
    UNKNOWN = "UNKNOWN"


class BreakoutState(StrEnum):
    NONE = "NONE"
    BREAKOUT = "BREAKOUT"
    RETEST = "RETEST"
    FALSE_BREAKOUT = "FALSE_BREAKOUT"


class ExecutionAction(StrEnum):
    ENTER = "ENTER"
    WAIT = "WAIT"
    NO_CHASE = "NO_CHASE"
    RECALCULATE = "RECALCULATE"
    NO_TRADE = "NO_TRADE"


class ActualTradeAction(StrEnum):
    HOLD = "HOLD"
    MOVE_STOP = "MOVE_STOP"
    BREAK_EVEN = "BREAK_EVEN"
    LOCK_PROFIT = "LOCK_PROFIT"
    PARTIAL_CLOSE = "PARTIAL_CLOSE"
    REDUCE = "REDUCE"
    FULL_CLOSE = "FULL_CLOSE"
    CANCEL = "CANCEL"


class ActualTradeStatus(StrEnum):
    OPEN = "OPEN"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"


class DegradationStatus(StrEnum):
    NOT_CONFIGURED = "NOT_CONFIGURED"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    STABLE = "STABLE"
    MODEL_CONFIDENCE_REDUCED = "MODEL_CONFIDENCE_REDUCED"


class SetupLifecycleStatus(StrEnum):
    ACTIVE = "ACTIVE"
    WATCH = "WATCH"
    DEGRADED = "DEGRADED"
    SHADOW_ONLY = "SHADOW_ONLY"
    RETIRED = "RETIRED"


class RegimePerformanceStatus(StrEnum):
    AVAILABLE = "AVAILABLE"
    REGIME_PERFORMANCE_UNKNOWN = "REGIME_PERFORMANCE_UNKNOWN"


class KillSwitchReason(StrEnum):
    ABNORMAL_MARKET = "ABNORMAL_MARKET"
    DATA_LOSS = "DATA_LOSS"
    DATA_SLA_FAIL = "DATA_SLA_FAIL"
    EXTREME_SPREAD = "EXTREME_SPREAD"
    VOLATILITY_SPIKE = "VOLATILITY_SPIKE"
    UNEXPECTED_EVENT = "UNEXPECTED_EVENT"
    MODEL_DEGRADATION = "MODEL_DEGRADATION"
    ABNORMAL_LOSS_STREAK = "ABNORMAL_LOSS_STREAK"
    UNRELIABLE_STATISTICS = "UNRELIABLE_STATISTICS"
    JOURNAL_ERROR = "JOURNAL_ERROR"
    EXECUTION_UNCERTAINTY = "EXECUTION_UNCERTAINTY"


class AuditGate(StrEnum):
    DATA = "DATA"
    DATA_SLA = "DATA_SLA"
    MICROSTRUCTURE = "MICROSTRUCTURE"
    MARKET_TREND = "MARKET_TREND"
    SETUP = "SETUP"
    FUNDAMENTAL_NEWS = "FUNDAMENTAL_NEWS"
    LIQUIDITY = "LIQUIDITY"
    ENTRY_STOP_TP = "ENTRY_STOP_TP"
    PATH_TO_TP = "PATH_TO_TP"
    COSTS = "COSTS"
    EXECUTION = "EXECUTION"
    RISK_BUDGET = "RISK_BUDGET"
    PORTFOLIO_CORRELATION = "PORTFOLIO_CORRELATION"
    OPPORTUNITY_COST = "OPPORTUNITY_COST"
    JOURNAL = "JOURNAL"
    CALIBRATION = "CALIBRATION"
    ADVERSARIAL = "ADVERSARIAL"
    REPRODUCIBILITY = "REPRODUCIBILITY"
    STRATEGY_VERSION = "STRATEGY_VERSION"


class AuditGateResult(StrEnum):
    PASS = "PASS"
    FAIL = "FAIL"
    NOT_REQUIRED = "NOT_REQUIRED"


class V24Classification(StrEnum):
    PRODUCTION_QUALIFIED = "PRODUCTION_QUALIFIED"
    STATISTICALLY_QUALIFIED_70 = "STATISTICALLY_QUALIFIED_70"
    STRUCTURALLY_QUALIFIED = "STRUCTURALLY_QUALIFIED"
    WATCH = "WATCH"
    SHADOW = "SHADOW"
    MODEL_CANDIDATE = "MODEL_CANDIDATE"
    NO_TRADE = "NO_TRADE"
    REJECT = "REJECT"
    CANCEL = "CANCEL"


class ThesisStatus(StrEnum):
    STRONG = "STRONG"
    VALID = "VALID"
    WEAKENING = "WEAKENING"
    INVALID = "INVALID"


class StopManagementState(StrEnum):
    INITIAL_RISK = "INITIAL_RISK"
    REDUCED_RISK = "REDUCED_RISK"
    BREAK_EVEN = "BREAK_EVEN"
    PROTECTED_PROFIT = "PROTECTED_PROFIT"
    INCREASING_PROTECTED_PROFIT = "INCREASING_PROTECTED_PROFIT"
    EXIT = "EXIT"


class PositionAdvisoryAction(StrEnum):
    HOLD = "HOLD"
    MOVE_STOP = "MOVE_STOP"
    PARTIAL_CLOSE_REVIEW = "PARTIAL_CLOSE_REVIEW"
    EXIT_REVIEW = "EXIT_REVIEW"
    EXIT = "EXIT"
    VERIFY_DATA = "VERIFY_DATA"
